meta_product_name: "LucAgathe"
meta_title: "Mariage Agathe & Lucas"
meta_description: "Toutes les infos pour le jour J"
meta_image: "wedding.ico"                           # Une image dans votre dossier app/assets/images/

